geopaths/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pathgame.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

pathgame/urls.py
from django.urls import path
from . import views


app_name = "pathgame"

urlpatterns = [
    path("", views.index, name="index"),
    
    path("user_page/<int:user_id>/", views.user_page, name="user_page"),
    
    path("board/creator/", views.board_creator, name="board_creator"),
    path("board/edit/<int:pk>/", views.board_edit, name="board_edit"),
    path("board/preview/<int:pk>/", views.board_preview, name="board_preview"),
    path("board/list/", views.board_list, name="board_list"),
    path("board/delete/<int:pk>/", views.board_delete, name="board_delete"),
    path("board/save/", views.board_save, name="board_save"),
    path("board/update_cell/", views.update_board_cell, name="update_board_cell"),
    
    path("subboard/editor/<int:pk>/", views.subboard_editor, name="subboard_editor"),
    path("subboard/update_name/<int:pk>/", views.update_subboard_name, name="update_subboard_name"),
    path("subboard/create/", views.subboard_create, name="subboard_create"),
    path("subboard/delete/<int:pk>/", views.subboard_delete, name="subboard_delete"),
    path("subboard/path/create/", views.create_path, name="create_path"),
    path("subboard/path/delete/", views.delete_path, name="delete_path"),
    
    path("sse/notifications/", views.sse_notifications, name="sse_notifications"),
    
    path('login/', views.custom_login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
]

pathgame/models.py
from django.db import models
from django.contrib.auth.models import User

class Board(models.Model):
    name = models.CharField(max_length=50)
    width = models.PositiveIntegerField()
    height = models.PositiveIntegerField()
    
    type = models.PositiveSmallIntegerField(choices=[
        (3, 'Triangle'),
        (4, 'Square'),
        (6, 'Hexagon'),
    ])
    
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='boards')
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class SubBoard(models.Model):
    name = models.CharField(max_length=50)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='subboards')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subboards')

    def __str__(self):
        return f"SubBoard {self.id} of {self.board.owner}"

class BoardPoint(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='points')
    row = models.PositiveIntegerField()
    col = models.PositiveIntegerField()
    color = models.CharField(max_length=7, default="#FFFFFF")
    
    class Meta:
        unique_together = ('board', 'row', 'col')

    def __str__(self):
        return f"Point ({self.row}, {self.col})"


class Path(models.Model):
    board = models.ForeignKey(SubBoard, on_delete=models.CASCADE, related_name='paths')
    color = models.CharField(max_length=7, default="#000000")

    def __str__(self):
        return f"Path {self.id} from Board {self.board.id}"


class PathPoint(models.Model):
    path = models.ForeignKey(Path, on_delete=models.CASCADE, related_name='points')
    row = models.PositiveIntegerField()
    col = models.PositiveIntegerField()
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']
        unique_together = ('path', 'order')

    def __str__(self):
        return f"Point {self.order}. ({self.row}, {self.col})"

pathgame/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import PermissionDenied
from django.forms.models import model_to_dict
from django.http import JsonResponse, StreamingHttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

import time
import json
import pathgame.utils as utils

from .models import Board, User, BoardPoint, SubBoard, Path, PathPoint


def index(request):
    return render(request, "pathgame/index.html")


@login_required
def user_page(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    if request.user != user and not request.user.is_staff:
        raise PermissionDenied
    
    user_boards = user.boards.all()
    user_subboards = user.subboards.all()
    
    context = {
        "boards": user_boards,
        "subboards": user_subboards,
        "prev_page": 'pathgame:index',
        "prev_page_label": 'Go to the Maps List',
    }
    return render(request, "pathgame/user_page.html", context)

@login_required
def board_creator(request):
    return render(request, "pathgame/board_creator.html")


@login_required
def board_save(request):
    if request.method == 'POST':
        try:
            name = request.POST.get('name', 'Untitled').strip()
            width = int(request.POST.get('width', 10))
            height = int(request.POST.get('height', 10))
            shape = int(request.POST.get('type', 'square'))

            if not (2 <= width <= 30 and 2 <= height <= 30):
                messages.error(request, "Width and height must be between 2 and 30.")
                return redirect('pathgame:board_creator')

            if shape not in (3, 4, 6):
                messages.error(request, "Invalid shape type selected.")
                return redirect('pathgame:board_creator')

            board = Board.objects.create(
                name=name or "Untitled",
                width=width,
                height=height,
                type=shape,
                creator=request.user
            )
            messages.success(request, "Board created successfully!")
            return redirect('pathgame:board_edit', pk=board.pk)

        except (ValueError, TypeError):
            messages.error(request, "Invalid form submission.")
            return redirect('pathgame:board_creator')

    return redirect('pathgame:board_creator')


@csrf_exempt
@login_required
def update_board_cell(request):
    if request.method != 'POST':
        return JsonResponse({'error': 'Invalid method'}, status=405)

    try:
        data = json.loads(request.body)
        board_id = int(data.get('board'))
        color_map = data.get('color_map')

        colors = {}
        for row_index, row in enumerate(color_map):
            for col_index, value in enumerate(row):
                if value not in colors.keys():
                    colors[value] = []
                colors[value].append((row_index, col_index))
        
        for col in colors.keys():
            if len(colors[col]) != 2 and col != "":
                error_msg = "For each color there should be 0 or 2 points."
                return JsonResponse({'status': 'failure', 'message': error_msg})
                
        
        board = Board.objects.get(pk=board_id, creator=request.user)
        board.subboards.all().delete()

        for color in colors.keys():
            for row, col in colors[color]:
                if color == "":
                    BoardPoint.objects.filter(board=board, row=row, col=col).delete()
                else:
                    BoardPoint.objects.update_or_create(board=board, row=row, col=col, color=color)

        return JsonResponse({'status': 'success'})

    except Board.DoesNotExist:
        return JsonResponse({'error': 'Board not found or permission denied'}, status=403)

    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@login_required
def board_edit(request, pk):
    board = get_object_or_404(Board, pk=pk, creator=request.user)
    poly_points = []
    for y in range(board.height + 1):
        for x in range(board.width + 1):
            poly_points.append((100 * x / board.width, 100 * y / board.height))
            
    board_points_list = board.points.all()
    board_points = [model_to_dict(point) for point in board_points_list]

    colors = set()
    for point in board_points:
        colors.add(point['color'])

    colors.update(["#FF0000", "#00FF00", "#0000FF", "#FF00FF", "#FFFF00", "#00FFFF"])
    colors = sorted(colors, key=lambda c: utils.hex_to_hsl(c)[0])
    
    context = {
        "board": model_to_dict(board),
        "poly_points": poly_points,
        "board_points": board_points,
        "colors": colors,
        "author": board.creator,
    }
    return render(request, 'pathgame/board_edit.html', context)

@login_required
def board_delete(request, pk):
    board = get_object_or_404(Board, pk=pk, creator=request.user)
    if request.method == 'POST':
        board.delete()
        return redirect('pathgame:user_page', user_id=request.user.id)
    return redirect('pathgame:user_page', user_id=request.user.id)



def board_list(request):
    boards = Board.objects.all()
    context = {
        'boards': boards
    }
    return render(request, 'pathgame/board_list.html', context)



def board_preview(request, pk):
    board = get_object_or_404(Board, pk=pk)
    poly_points = []
    for y in range(board.height + 1):
        for x in range(board.width + 1):
            poly_points.append((100 * x / board.width, 100 * y / board.height))
            
    board_points_list = board.points.all()
    board_points = [model_to_dict(point) for point in board_points_list]

    colors = set()
    for point in board_points:
        colors.add(point['color'])
    colors = list(colors)
    context = {
        "board": model_to_dict(board),
        "poly_points": poly_points,
        "board_points": board_points,
        "colors": colors,
        "author": board.creator,
        "user_is_author": board.creator == request.user
    }
    return render(request, 'pathgame/board_preview.html', context)


@csrf_exempt
@login_required
def subboard_create(request):
    if request.method == 'POST':
        try:
            board_id = request.POST.get('board_id')
            subboard = SubBoard.objects.create(
                name="Untitled",
                board=Board.objects.get(pk=board_id),
                owner=request.user
            )
            
            messages.success(request, "SubBoard created successfully!")
            return redirect('pathgame:subboard_editor', pk=subboard.pk)

        except (ValueError, TypeError):
            messages.error(request, "Invalid form submission.")
            return redirect('pathgame:board_list')

    return redirect('pathgame:board_list')

@login_required
def subboard_delete(request, pk):
    subboard = get_object_or_404(SubBoard, pk=pk, owner=request.user)
    if request.method == 'POST':
        subboard.delete()
        return redirect('pathgame:user_page', user_id=request.user.id)
    return redirect('pathgame:user_page', user_id=request.user.id)




@login_required
def subboard_editor(request, pk):
    subboard = get_object_or_404(SubBoard, pk=pk, owner=request.user)
    
    board = subboard.board
    
    poly_points = []
    for y in range(board.height + 1):
        for x in range(board.width + 1):
            poly_points.append((100 * x / board.width, 100 * y / board.height))
            
    board_points_list = board.points.all()
    board_points = [model_to_dict(point) for point in board_points_list]

    colors = set()
    for point in board_points:
        colors.add(point['color'])
    colors = list(colors)
    
    paths = []
    for path_obj in subboard.paths.all():
        path = {
            'color': path_obj.color,
            'points': []
        }
        for point in path_obj.points.order_by('order'):
            path['points'].append((point.row, point.col))
        paths.append(path)
    
    context = {
        'subboard': model_to_dict(subboard),
        'board': model_to_dict(subboard.board),
        "poly_points": poly_points,
        "board_points": board_points,
        "colors": colors,
        "paths": paths,
        "board_author": board.creator,
        "subboard_author": subboard.owner
    }
    return render(request, 'pathgame/subboard_editor.html', context)




@login_required
def update_subboard_name(request, pk):
    subboard = get_object_or_404(SubBoard, id=pk, owner=request.user)
    if request.method == 'POST':
        new_name = request.POST.get('name', '').strip()
        if new_name:
            subboard.name = new_name
            subboard.save()
    return redirect('pathgame:subboard_editor', pk=subboard.pk)



@csrf_exempt
@login_required
def create_path(request):
    if request.method != 'POST':
        return JsonResponse({'error': 'Invalid method'}, status=405)

    try:
        data = json.loads(request.body)
        path_got = data.get('path')
        subboard_id = int(data.get('subboard'))
        subboard = get_object_or_404(SubBoard, id=subboard_id, owner=request.user)
        
        board_id = subboard.board.pk
        board_point = BoardPoint.objects.filter(board=board_id, row=int(path_got[0]['row']), col=int(path_got[0]['col'])).first()
        color = board_point.color
        
        path_obj = Path.objects.create(
            board = subboard,
            color = color,
        )
        for id, point in enumerate(path_got):
            row, col = int(point['row']), int(point['col'])
            PathPoint.objects.create(
                path = path_obj,
                row = row,
                col = col,
                order = id + 1,
            )
            

pathgame/templates/pathgame/base.html
{% load static tailwind_tags %}

<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{{ user.id|json_script:"user-id" }}

<!DOCTYPE html>
<html lang="en" class="bg-navy text-gray-100">
<head>
    <meta charset="UTF-8">
    <title>GeoPaths</title>
    {% tailwind_css %}
</head>
<body class="bg-black">

    <div id="notifications-container" class="fixed bottom-4 w-60 right-4 flex flex-col gap-2 z-50"></div>
    
    <header class="w-full h-20 bg-black flex items-center justify-between px-8 shadow-md border-b-2 border-sky-300">
        <div class="flex items-center space-x-4">
            <a href="{% url 'pathgame:index' %}" class="flex items-center">
                <div class="h-13 w-13 bg-dirty-red flex items-center justify-center border-1">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/c/c1/Penrose-dreieck.svg" alt="CaveMaps Logo" class="h-10 w-10" />
                </div>
                <div class="flex flex-col ml-2">
                    <span class="text-xl font-bold text-white leading-none">GeoPaths</span>
                    <h1 class="text-sm text-white leading-none">{% block title %}{% endblock %}</h1>
                </div>
            </a>
        </div>
    
        <div class="relative ml-4">
            {% if user.is_authenticated %}
                <button onclick="toggleDropdown()" class="flex items-center focus:outline-none hover:cursor-pointer">
                    <img src="https://img.icons8.com/?size=100&id=83190&format=png&color=ffffff"
                         alt="Profile"
                         class="h-8 w-8 rounded-full border-2 border-white hover:opacity-80 transition" />
                </button>
        
                <div id="accountDropdown" class="hidden absolute right-0 mt-2 w-48 bg-black rounded shadow-lg z-50 text-white border-1">
                    <div class="px-4 py-2 border-b">
                        <p class="font-medium {% if user.is_superuser %}text-red-500 {% endif %}">{{ user.username }}</p>
                    </div>
                    <a href="{% url 'pathgame:user_page' user.id %}" class="flex items-center px-4 py-2 hover:bg-navy space-x-2">
                        <span>My page</span>
                    </a>
                    <form method="post" action="{% url 'pathgame:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="flex items-center w-full text-left px-4 py-2 hover:bg-navy hover:cursor-pointer space-x-2">
                            <span>Logout</span>
                        </button>
                    </form>
                </div>
                <script>
                    function toggleDropdown() {
                        const dropdown = document.getElementById('accountDropdown');
                        dropdown.classList.toggle('hidden');
                    }
            
                    document.addEventListener('click', function(event) {
                        const dropdown = document.getElementById('accountDropdown');
                        const button = event.target.closest('button');
                        if (!dropdown.contains(event.target) && (!button || !button.onclick)) {
                            dropdown.classList.add('hidden');
                        }
                    });
                </script>
            {% else %}
                <a href="{% url 'pathgame:login' %}?next={{ request.path }}" class="bg-navy text-sky-200 hover:text-white px-4 py-2 rounded border-1">
                    Login
                </a>
            {% endif %}
        </div>
    
    </header>

    <main class="max-w-8xl mx-auto bg-gradient-to-b from-navy to-black p-8 space-y-8 flex flex-col items-center text-sky-300">
        {% block content %}{% endblock %}
    </main>
    <script type="module" src="{% static 'js/dist/base.js' %}"></script>
</body>
</html>

pathgame/templates/pathgame/board_creator.html
{% extends 'pathgame/base.html' %}
{% load static %}
{% block title %}Board Creator{% endblock %}
{% block content %}
<div class="flex">
    <form method="POST" draggable="false" action="{% url 'pathgame:board_save' %}" class="select-none flex flex-col gap-4 mr-8">
        {% csrf_token %}
        <div class="flex items-center">
            <label for="sliderWidth" class="mr-2">Width:</label>
            <input type="range" id="sliderWidth" name="width" min="2" max="30" value="10" class="w-full">
            <span id="sliderWidthValue" class="ml-2"></span>
        </div>

        <div class="flex items-center">
            <label for="sliderHeight" class="mr-2">Height:</label>
            <input type="range" id="sliderHeight" name="height" min="2" max="30" value="10" class="w-full">
            <span id="sliderHeightValue" class="ml-2"></span>
        </div>

        <div>
            <label for="select_shape" class="block mb-1">Shape:</label>
            <select id="select_shape" name="type" class="border p-2 bg-black text-white rounded hover:cursor-pointer">
                <option value="3" class="hover:cursor-pointer">Triangles</option>
                <option value="4" class="hover:cursor-pointer">Squares</option>
                <option value="6" class="hover:cursor-pointer" selected="selected">Hexagons</option>
            </select>
        </div>

        <div>
            <label for="board_name" class="block mb-1">Board Name:</label>
            <input type="text" name="name" id="board_name" value="Untitled" class="text-white border p-2 rounded w-full">
        </div>

        <button id="submit_board_btn" type="submit" class ="bg-black border-black border-1 text-white p-2 rounded hover:cursor-pointer hover:border-white">Start adding points</button>
    </form>

    <svg id="grid" width="1000" height="600"></svg>
</div>

<script type="module" src="{% static 'js/dist/board-creator.js' %}"></script>
{% endblock %}

pathgame/templates/pathgame/board_edit.html
{% extends 'pathgame/base.html' %}
{% load static %}

{% block title %}Board Editor{% endblock %}

{% block content %}

<div class="mb-4 text-8xl p-3 gap-2 flex flex-col">
    <p class="font-bold text-hollow">{{ board.name }}</p>
    <div class="text-left text-base mt-2">
        <a href="{% url 'pathgame:board_preview' board.id %}" class="inline-block px-4 py-2 text-xs bg-black text-gray-400 rounded transition hover:underline">
            Click to see the Preview
        </a>
    </div>
</div>

{{ board|json_script:"board-data" }}
{{ board_points|json_script:"board-points" }}

<div class="flex flex-row gap-10">
    <div class="w-80 bg-black border-2 p-2 flex flex-col gap-2">
        <div class="color h-12 w-full border-3 border-blue-300 border-double p-1 hover:cursor-pointer flex justify-center items-center" color="">
            <div class="h-full w-20 font-extrabold aspect-square text-center text-2xl select-none" style="background-color: {{ color }};">X</div>
        </div>

        <div class="flex-1 overflow-y-auto">
            <div id="colorGrid" class="grid grid-cols-3 gap-2 pr-1">
                {% for color in colors %}
                    <div class="color h-12 border-3 border-black border-double p-3 hover:cursor-pointer flex items-center justify-center" color="{{ color }}">
                        <div class="h-full w-15" style="background-color: {{ color }};" title="{{ color }}"></div>
                    </div>
                {% endfor %}
            </div>
        </div>
        
        <div class="w-full text-center mt-2">
            <input id="colorPicker" type="color" class="cursor-pointer border border-gray-400 rounded" />
            <button id="addColorButton" class="mt-2 ml-2 px-2 py-1 bg-blue-700 text-white rounded hover:bg-blue-800 hover:cursor-pointer">Add Color</button>
        </div>
        <button id="saveButton" class="mt-2 ml-2 px-2 py-1 bg-blue-700 text-white rounded hover:bg-blue-800 hover:cursor-pointer">Save Changes</button>
    </div>

    <svg id="grid" width="1000" height="600" class="select-none"></svg>
</div>

<p class="text-red-700">
    <span class="font-bold">Warning:</span> every save of the board will result in deletion of every subboard linked to this board
</p>

<script type="module" src="{% static 'js/dist/board-edit.js' %}"></script>

{% endblock %}

pathgame/templates/pathgame/board_list.html
{% extends 'pathgame/base.html' %}

{% block title %}Board List{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-6 text-center">Board List</h1>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for board in boards %}
        <a href="{% url 'pathgame:board_preview' board.id %}" class="block">
            <div class="rounded-2xl shadow-md p-6 hover:shadow-xl transition duration-300 border-1">
                <h2 class="text-xl font-semibold">{{ board.name }}</h2>
                <p class="mt-2"><strong>Size:</strong> {{ board.width }} x {{ board.height }}</p>
                <p class=""><strong>Type:</strong> 
                    {% if board.type == 3 %} Triangle
                    {% elif board.type == 4 %} Square
                    {% elif board.type == 6 %} Hexagon
                    {% else %} Unknown
                    {% endif %}
                </p>
                <p class="text-sm text-gray-400 mt-2">Created by <strong>{{ board.creator.username }}</strong></p>
                <p class="text-xs text-gray-300">Updated {{ board.updated_at|date:"d M Y" }}</p>
            </div>
        </a>
        {% empty %}
        <div class="col-span-full text-center text-gray-400">
            No boards available.
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

pathgame/templates/pathgame/board_preview.html
{% extends 'pathgame/base.html' %}
{% load static %}

{% block title %}{{ author.username }}'s {{ board.name }}{% endblock %}

{% block content %}

<div class="mb-4 text-4xl p-4">
    <p class=""> 
        <span class="font-extrabold text-hollow text-9xl"> {{ board.name }} </span>
        <span class="font-extralight">by</span> 
        <span class="font-extralight"> {{ author.username }} </span>
    </p>
</div>

{{ board|json_script:"board-data" }}
{{ board_points|json_script:"board-points" }}

<svg id="grid" width="1200" height="800" class="select-none"></svg>

{% if user.is_authenticated %}
    <form method="POST" draggable="false" action="{% url 'pathgame:subboard_create' %}" class="select-none">
        {% csrf_token %}
        <input type="hidden" name="board_id" value="{{ board.id }}">
        <button id="submit_board_btn" type="submit" class ="bg-black border-2 p-2 hover:cursor-pointer w-250 hover:text-white">Create a subboard</button>
    </form>
    {% if user_is_author %}
        <a href="{% url 'pathgame:board_edit' board.id %}" class="inline-block bg-black border-2 p-2 hover:text-white w-250 text-center">
            Edit this board
        </a>
    {% endif %}

{% else %}
    <p class="text-gray-400">Log in to create a subboard.</p>
{% endif %}

<script type="module" src="{% static 'js/dist/board-preview.js' %}"></script>

{% endblock %}

pathgame/templates/pathgame/login.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en" class="text-gray-100">
    <head>
        <meta charset="UTF-8">
        <title>Login - Map Explorer</title>
        {% tailwind_css %}
    </head>
    <body class="bg-navy">

        <div class="min-h-screen flex items-center justify-center">
            <div class="p-8 rounded-xl shadow-lg space-y-6 max-w-md w-full bg-black border-1">
                <h2 class="text-2xl font-bold text-white text-center mb-4">Login to Map Explorer</h2>
                
                <form method="post" class="space-y-4">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <button type="submit" class="w-full bg-black hover:bg-navy hover:inset-ring-1 text-white px-4 py-2 rounded hover:cursor-pointer">
                        Login
                    </button>
                </form>
            </div>
        </div>

    </body>
</html>

pathgame/templates/pathgame/subboard_editor.html
{% extends 'pathgame/base.html' %}
{% load static %}

{% block title %}Subboard Editor{% endblock %}

{% block content %}

<div class="w-full flex flex-col items-center">
    <div class="relative w-9/10 h-20 flex items-center"> 
        <p class="font-bold absolute text-5xl px-4 text-hollow">Board "{{ board.name }}" <span class="text-2xl">by {{ board_author.username }}</span></p>
    </div>
    <form method="POST" action="{% url 'pathgame:update_subboard_name' subboard.id %}" class="space-y-2 flex flex-col">
        {% csrf_token %}
        <input type="text" id="subboard-name" name="name" value="{{ subboard.name }}" class="w-150 px-2 py-1 h-20 rounded text-center text-4xl">
        <p class="text-sm text-gray-500 self-center">by {{ subboard_author.username }}</p>
    </form>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const input = document.getElementById("subboard-name");

            function resizeInput() {
                input.style.width = ((input.value.length + 1) * 1) + "ch";
            }

            input.addEventListener("input", resizeInput);
            resizeInput();
        });
    </script>
</div>

{{ board|json_script:"board-data" }}
{{ board_points|json_script:"board-points" }}
{{ subboard|json_script:"subboard-data" }}
{{ paths|json_script:"paths-data" }}
<svg id="grid" width="1000" height="800" class="select-none" oncontextmenu="return false;"></svg>

<script type="module" src="{% static 'js/dist/subboard-editor.js' %}"></script>

{% endblock %}

pathgame/templates/pathgame/user_page.html
{% extends 'pathgame/base.html' %}

{% block title %}
    {{ user.username }}'s Page
{% endblock %}

{% block content %}
<div class="w-full max-w-4xl grid grid-cols-1 md:grid-cols-2 gap-8">
    <!-- Boards Column -->
    <div>
        <h2 class="text-xl font-bold mb-4 border-b border-sky-500 pb-2">Boards</h2>
        {% if boards %}
            <ul class="space-y-2 list-disc list-inside">
                {% for board in boards %}
                    <li class="flex justify-between items-center">
                        <a href="{% url 'pathgame:board_edit' board.id %}" class="text-sky-300 hover:underline">
                            {{ board.name }}
                        </a>
                        <form action="{% url 'pathgame:board_delete' board.id %}" method="post" class="inline">
                            {% csrf_token %}
                            <button type="submit" class="text-red-400 hover:underline ml-2 text-sm hover:cursor-pointer">Delete</button>
                        </form>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-gray-400">None</p>
        {% endif %}
    </div>

    <!-- Subboards Column -->
    <div>
        <h2 class="text-xl font-bold mb-4 border-b border-sky-500 pb-2">Subboards</h2>
        {% if subboards %}
            <ul class="space-y-2 list-disc list-inside">
                {% for subboard in subboards %}
                    <li class="flex justify-between items-center">
                        <a href="{% url 'pathgame:subboard_editor' subboard.id %}" class="text-sky-300 hover:underline">
                            {{ subboard.name }}
                        </a>
                        <form action="{% url 'pathgame:subboard_delete' subboard.id %}" method="post" class="inline">
                            {% csrf_token %}
                            <button type="submit" class="text-red-400 hover:underline ml-2 text-sm hover:cursor-pointer">Delete</button>
                        </form>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-gray-400">None</p>
        {% endif %}
    </div>

</div>
{% endblock %}